### ISSUE TITLE
Migrate Text Renderer to Mixin

### ISSUE THREAD

**Issue by sinender** [redstone-llc/Hysentials-java#7]
## Enhancement Description
Change how Fancy Formatting is done to improve performance, ease of use, etc.

## TODO Tasks

- [x] Replacements
- [ ] Image Icons (Is it even possible?)
  - [x] Emojis (Move to chat checking instead)
  - [x] Rank Icons
  - [x] Faster loading and use
  - [x] **TEST**
 - [ ] Hex Coloring
   - [ ] Think of a new format?
   - [x] Implement
   - [ ] **TEST**
 - [ ] Numbered Things
   - [ ] Think of a new format?
   - [ ] Implement
   - [ ] Faster?
   - [ ] **TEST**
- [ ] Chat formatting issues
  - [x] Ensure fancy formatting doesn't break chat
  - [ ] **SO MUCH TESTING**
  
  ### Updates
  - 8/12/24 Basically trying to see if its even possible. Found a roadblock with mixin already hmph
